### ISSUE TITLE
Fragmentation failed

### ISSUE THREAD

**Issue by okbckim** [openforcefield/openff-fragmenter#177]
**Description**

Please describe what you were trying to do, what you expected to happen, and what happened instead.

This molecule failed in fragmentation stage.

**Reproduction**
[test.tar.gz](https://github.com/openforcefield/openff-bespokefit/files/15165733/test.tar.gz)

Please include a [minimally reproducing example](https://stackoverflow.com/help/minimal-reproducible-example) of this bug.
 BEFLOW_OPTIMIZER_KEEP_FILES=True openff-bespoke executor run --directory fitting --n-fragmenter-workers 2 --n-optimizer-workers 2  --n-qc-compute-workers 2 --qc-compute-n-cores 1 --file test2.sdf --output test2.sdf.json --output-force-field test2.sdf.offxml --workflow "default" --default-qc-spec  xtb gfn2xtb none

BEFLOW_OPTIMIZER_KEEP_FILES=True openff-bespoke executor run --directory fitting --n-fragmenter-workers 2 --n-optimizer-workers 2  --n-qc-compute-workers 2 --qc-compute-n-cores 1 --file test3.sdf --output test3.sdf.json --output-force-field test3.sdf.offxml --workflow "default" --default-qc-spec  xtb gfn2xtb none

**Output**

[✓] bespoke executor launched

1. preparing the bespoke workflow

[✓] 1 molecules found
[✓] fitting schemas generated

2. submitting the workflow

[✓] the following workflows were submitted
┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━━━━━┓
┃ ID ┃ SMILES                       ┃ NAME  ┃ FILE      ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━┩
│ 2  │ c1cc(C2C[C@@H]3C[C@@H]3C2)n1 │ test2 │ test2.sdf │
└────┴──────────────────────────────┴───────┴───────────┘

3. running the fitting pipeline

[x] fragmentation failed

 {"type": "ValueError", "message": "not enough values to unpack (expected 2, got 0)", "traceback": "Traceback (most recent call last):\n  File
 \"/home/bckim/mambaforge/envs/bespokefit-env/lib/python3.10/site-packages/celery/app/trace.py\", line 477, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File
 \"/home/bckim/mambaforge/envs/bespokefit-env/lib/python3.10/site-packages/celery/app/trace.py\", line 760, in __protected_call__\n    return self.run(*args, **kwargs)\n  File
 \"/home/bckim/mambaforge/envs/bespokefit-env/lib/python3.10/site-packages/openff/bespokefit/executor/services/fragmenter/worker.py\", line 36, in fragment\n
 fragmenter.fragment(molecule, target_bond_smarts=target_bond_smarts)\n  File
 \"/home/bckim/mambaforge/envs/bespokefit-env/lib/python3.10/site-packages/openff/fragmenter/fragment.py\", line 916, in fragment\n    result = self._fragment(molecule,
 target_bond_smarts)\n  File \"/home/bckim/mambaforge/envs/bespokefit-env/lib/python3.10/site-packages/openff/fragmenter/fragment.py\", line 1019, in _fragment\n    fragments =
 {\n  File \"/home/bckim/mambaforge/envs/bespokefit-env/lib/python3.10/site-packages/openff/fragmenter/fragment.py\", line 1020, in <dictcomp>\n    bond: self._build_fragment(\n
 File \"/home/bckim/mambaforge/envs/bespokefit-env/lib/python3.10/site-packages/openff/fragmenter/fragment.py\", line 1204, in _build_fragment\n    fragment,
 has_new_stereocenter = cls._add_next_substituent(\n  File \"/home/bckim/mambaforge/envs/bespokefit-env/lib/python3.10/site-packages/openff/fragmenter/fragment.py\", line 1409,
 in _add_next_substituent\n    neighbour_atom_and_bond = cls._select_neighbour_by_path_length(\n  File
 \"/home/bckim/mambaforge/envs/bespokefit-env/lib/python3.10/site-packages/openff/fragmenter/fragment.py\", line 1264, in _select_neighbour_by_path_length\n    path_lengths_1,
 path_lengths_2 = zip(\nValueError: not enough values to unpack (expected 2, got 0)\n"}

Please include the output, including full tracebacks of any errors, resulting from the reproduction.

**Software versions**
[✓] bespoke executor launched

1. preparing the bespoke workflow

[✓] 1 molecules found
[✓] fitting schemas generated

2. submitting the workflow

[✓] the following workflows were submitted
┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━━━━━┓
┃ ID ┃ SMILES                       ┃ NAME  ┃ FILE      ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━┩
│ 2  │ c1cc(C2C[C@@H]3C[C@@H]3C2)n1 │ test2 │ test2.sdf │
└────┴──────────────────────────────┴───────┴───────────┘

3. running the fitting pipeline

[x] fragmentation failed

 {"type": "ValueError", "message": "not enough values to unpack (expected 2, got 0)", "traceback": "Traceback (most recent call last):\n  File
 \"/home/bckim/mambaforge/envs/bespokefit-env/lib/python3.10/site-packages/celery/app/trace.py\", line 477, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File
 \"/home/bckim/mambaforge/envs/bespokefit-env/lib/python3.10/site-packages/celery/app/trace.py\", line 760, in __protected_call__\n    return self.run(*args, **kwargs)\n  File
 \"/home/bckim/mambaforge/envs/bespokefit-env/lib/python3.10/site-packages/openff/bespokefit/executor/services/fragmenter/worker.py\", line 36, in fragment\n
 fragmenter.fragment(molecule, target_bond_smarts=target_bond_smarts)\n  File
 \"/home/bckim/mambaforge/envs/bespokefit-env/lib/python3.10/site-packages/openff/fragmenter/fragment.py\", line 916, in fragment\n    result = self._fragment(molecule,
 target_bond_smarts)\n  File \"/home/bckim/mambaforge/envs/bespokefit-env/lib/python3.10/site-packages/openff/fragmenter/fragment.py\", line 1019, in _fragment\n    fragments =
 {\n  File \"/home/bckim/mambaforge/envs/bespokefit-env/lib/python3.10/site-packages/openff/fragmenter/fragment.py\", line 1020, in <dictcomp>\n    bond: self._build_fragment(\n
 File \"/home/bckim/mambaforge/envs/bespokefit-env/lib/python3.10/site-packages/openff/fragmenter/fragment.py\", line 1204, in _build_fragment\n    fragment,
 has_new_stereocenter = cls._add_next_substituent(\n  File \"/home/bckim/mambaforge/envs/bespokefit-env/lib/python3.10/site-packages/openff/fragmenter/fragment.py\", line 1409,
 in _add_next_substituent\n    neighbour_atom_and_bond = cls._select_neighbour_by_path_length(\n  File
 \"/home/bckim/mambaforge/envs/bespokefit-env/lib/python3.10/site-packages/openff/fragmenter/fragment.py\", line 1264, in _select_neighbour_by_path_length\n    path_lengths_1,
 path_lengths_2 = zip(\nValueError: not enough values to unpack (expected 2, got 0)\n"}

- Which operating system and version are you using? ubuntu
- How did you install BespokeFit? following manual
- Are you using Apple Silicon? If so, are you running BespokeFit in Rosetta (`osx-64`) or natively (`osx-arm64`)? No
- What is the output of running `conda list`?

<details><summary>Output of <code>conda list</code></summary><pre>

Please place the output of `conda list` here

</pre></details>

**Comment by j-wags** [comment]
I've made a fresh install of the env and verified that this works with fragmenter 0.2.2 (though I did need to delete the `fitting/` folder so it wouldn't keep loading outdated results. Please feel free to reopen this issue if this didn't fix it!
